menu:
    博文: /
    归档: /archives/
    开源贡献: /os/
   # 生活: /categories/live/
   # 摄影: /categories/film/
    关于: /about/

widgets:
- category
- tag
- tagcloud
- archive

# count
show_count: true
favicon: /images/favicon.ico
logo: /images/logo.png

# Comment
changyan: 
yungentie: 
disqus:
duoshuo: 


# Analytics
# google-analytics:
ga: UA-65933410-1

# Copyright Infomation
startyear: 2016

